version: '3.8'

services:
  backend:
    container_name: backend-dev
    image: backend-dev
    build:
      context: .
      dockerfile: Dockerfile.dev
    env_file:
      - .env.dev
    volumes:
      - .:/app  # แชร์โค้ดแบบ Live Sync
      - ./db.sqlite3:/app/db.sqlite3  # แชร์ไฟล์ฐานข้อมูล SQLite
    ports:
      - "8000:8000"
    environment:
      - DJANGO_SETTINGS_MODULE=backend.settings
    command: python manage.py runserver 0.0.0.0:8000
