# ใช้ Python 3.11 เป็น Base Image
FROM python:3.11

# ติดตั้ง netcat
RUN apt-get update && apt-get install -y netcat-openbsd

# กำหนด Working Directory
WORKDIR /app

# คัดลอก requirements.txt และติดตั้ง dependencies
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# คัดลอกไฟล์ .env
COPY .env .env

# กำหนด environment variables
ENV PYTHONUNBUFFERED=1

# รันเซิร์ฟเวอร์ Django
CMD ["sh", "-c", "python manage.py migrate  && python manage.py loaddata data.json && python manage.py runserver 0.0.0.0:8000"]
