# ใช้ Python 3.11 เป็น Base Image
FROM python:3.11

# ตั้งค่าตัวแปร
ENV PYTHONUNBUFFERED=1

# กำหนด Working Directory
WORKDIR /app

# คัดลอกไฟล์ requirements.txt และติดตั้ง dependencies
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# คัดลอกโค้ดทั้งหมดไปที่ Container
COPY . .

# คำสั่งเริ่มต้น ใช้ `runserver` เพื่อรัน API ในโหมดพัฒนา
CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]
